[{name:"Juan Peralta", aire: true},
{name:"Diegote", aire: true},
{name:"Dani Molinet", aire: true},
{name:"Nico Heredia", aire: true},
{name:"Eve", aire: true},
{name:"Gisela Vivas La Patria", aire: true},
{name:"Paula Herrero", aire: true},
{name:"Dani Rodriguez", aire: true},
{name:"Martin Pelado", aire: true},
{name:"Juan Manuel", aire: true},
{name:"Silvina", aire: true},
{name:"Leo Tioni", aire: true},
{name:"Guido", aire: true},
{name:"Tate", aire: true},
{name:"Andy", aire: true},
{name:"Cacu", aire: true},
{name:"Mati Crespo", aire: true},
{name:"Pato", aire: true},
{name:"Rodrigo Fuentes", aire: true},
{name:"Gonzo", aire: true},
{name:"Leo Elias", aire: true},
{name:"Nico Rodas", aire: true},
{name:"Mati (de Kinsser)", aire: true},
{name:"March", aire: true},
{name:"NaN", aire: true},
{name:"Seba", aire: true},
{name:"Bruno", aire: true}]
